version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
    networks:
      - app-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
